### PR TITLE
Add image+text examples, and update readme

### PR DESCRIPTION
**Pull request by vgmoose**
I added small examples in src/menu/MainWindowTv.cpp of creating a GuiImage and GuiText, the end result is this:
pie

It's commented out though, but to give people an idea of how to instantiate them.

### CODE REVIEW

**Comment by ghost** [comment]
+1

**Comment by vgmoose** [comment]
@Maschell do you not like pie :cry: 

If I had to guess, I'd say this hasn't been merged cause:

1. it's a commented out code example, which is kinda strange already
2. it's not really "good practice" to just dump the image+text in the constructor like this, they should be field variables and properly deinitialized
3. if they were field variables and properly initialized, them being commented out would only make it harder for the user to uncomment in several places.

I'll likely make another PR that won't come commented out, but still demonstrate basic text+image loading. (and there will be less pie)

**Comment by xhp-creations** [comment]
Why don't you fork the repo and create a branch with the tutorial stuff?

**Comment by vgmoose** [comment]
I have forked it, just haven't created a new branch: https://github.com/vgmoose/GX2_GUI_Template

I still think there's a better way to go about this than the pie+text though. In fact, maybe there should be several different examples, each a small step more sophisticated, all based off this repo as a base. They could be leading up to creating a small gx2 game in the last example, all commented with explanations.

**Comment by xhp-creations** [comment]
Well, I actually uncommented the sound in the rpx channel version, that way people could at least see (hear) it work that way.

**Pull request closed without merging**
